import '../chess_board.dart';
import '../chess_piece.dart';
import '../move_calculation/move_classes/move.dart';

/// Konvertiert einen UCI-String (z.B. "e2e4" oder "e7e8q") in ein [Move]-Objekt.
///
/// Konvention in ChessBoard:
/// - rank 0 ist die 8. Reihe (Schwarz)
/// - rank 7 ist die 1. Reihe (Weiß)
/// - file 0 ist die a-Linie
/// - file 7 ist die h-Linie
/// - tile = rank * 8 + file
Move uciToMove(String uci, ChessBoard board) {
  if (uci.length < 4 || uci.length > 5) {
    throw FormatException(
        'Ungültiges UCI-Format: String-Länge muss 4 oder 5 sein ($uci).');
  }

  // Castling special cases in UCI (if generated by some engines)
  if (uci == 'e1g1') return Move(60, 63);
  if (uci == 'e1c1') return Move(60, 56);
  if (uci == 'e8g8') return Move(4, 7);
  if (uci == 'e8c8') return Move(4, 0);

  int fromFile = uci.codeUnitAt(0) - 97; // 'a' = 97
  int fromRank = 8 - int.parse(uci[1]);
  int toFile = uci.codeUnitAt(2) - 97;
  int toRank = 8 - int.parse(uci[3]);

  if (fromFile < 0 ||
      fromFile > 7 ||
      fromRank < 0 ||
      fromRank > 7 ||
      toFile < 0 ||
      toFile > 7 ||
      toRank < 0 ||
      toRank > 7) {
    throw FormatException(
        'Ungültiges UCI-Format: Koordinaten außerhalb des Bretts ($uci).');
  }

  Move move = Move(fromRank * 8 + fromFile, toRank * 8 + toFile);

  if (uci.length == 5) {
    switch (uci[4]) {
      case 'q':
        move.promotionType = ChessPieceType.queen;
        break;
      case 'r':
        move.promotionType = ChessPieceType.rook;
        break;
      case 'b':
        move.promotionType = ChessPieceType.bishop;
        break;
      case 'n':
        move.promotionType = ChessPieceType.knight;
        break;
      default:
        throw FormatException(
            'Ungültiges UCI-Format: Unbekannter Promotion-Typ (${uci[4]}).');
    }
  }

  return move;
}
